In [50]:
import numpy as np
import pandas as pd

In [51]:
data = {
    'Name' :['jhon','anna','peter','linda'],
    'Age' :[28,34,29,42],
    'city' :['new york','paris','berlin','london'],
    'salary':[65000,75000,62000,80000]
}
df =pd.DataFrame(data)

In [52]:
df

    Name  Age      city  salary
0   jhon   28  new york   65000
1   anna   34     paris   75000
2  peter   29    berlin   62000
3  linda   42    london   80000

In [53]:
data_list =[
    ['jhon', 28 , 'new york ',65000],
    ['anna',34,'paris',70000],
    ['peter',29,'berlin',62000],
    ['linda',42,'london',80000]
]
df2 = pd.DataFrame(data_list)
columns = ['name','age','city','salary']

In [54]:
df2 = pd.DataFrame(data_list,columns=columns)
df2

    name  age       city  salary
0   jhon   28  new york    65000
1   anna   34      paris   70000
2  peter   29     berlin   62000
3  linda   42     london   80000

In [55]:
df2[['name','city']]

    name       city
0   jhon  new york
1   anna      paris
2  peter     berlin
3  linda     london

In [56]:
df2['designation'] = ['doctor','eng','doc','eng']
df2

    name  age       city  salary designation
0   jhon   28  new york    65000      doctor
1   anna   34      paris   70000         eng
2  peter   29     berlin   62000         doc
3  linda   42     london   80000         eng

In [57]:
a = df2.drop(['city','salary'],axis = 1)
a

    name  age designation
0   jhon   28      doctor
1   anna   34         eng
2  peter   29         doc
3  linda   42         eng

In [58]:
df2

    name  age       city  salary designation
0   jhon   28  new york    65000      doctor
1   anna   34      paris   70000         eng
2  peter   29     berlin   62000         doc
3  linda   42     london   80000         eng

In [59]:
df2

    name  age       city  salary designation
0   jhon   28  new york    65000      doctor
1   anna   34      paris   70000         eng
2  peter   29     berlin   62000         doc
3  linda   42     london   80000         eng

In [60]:
df2.loc[[0]]

   name  age       city  salary designation
0  jhon   28  new york    65000      doctor

In [61]:
##3 SUBSETS OF A PARTICULAR PORTION ###

df2.iloc[[0, 1]][['city', 'salary']]

        city  salary
0  new york    65000
1      paris   70000

In [62]:
df2.loc[[2, 3], ['name', 'age', 'city', 'salary']]

    name  age    city  salary
2  peter   29  berlin   62000
3  linda   42  london   80000

In [63]:
df.iloc[3]

Name       linda
Age           42
city      london
salary     80000
Name: 3, dtype: object

In [64]:
###CONDITIONAL SELECTION ###

In [65]:
## only want people with age above 30##

In [68]:

data = {
    'Name' :['jhon','anna','peter','linda'],
    'Age' :[28,34,29,42],
    'city' :['new york','paris','berlin','london'],
    'salary':[65000,75000,62000,80000]
}
df =pd.DataFrame(data)

In [69]:
df

    Name  Age      city  salary
0   jhon   28  new york   65000
1   anna   34     paris   75000
2  peter   29    berlin   62000
3  linda   42    london   80000

In [72]:
df[(df['Age'] > 30) & (df['city'] == 'paris')]

   Name  Age   city  salary
1  anna   34  paris   75000